apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: elastic-ingress
  namespace: elastic-system
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/hostname: <domain of your eleasticdomain>
spec:
  rules:
  - host: <domain of your eleasticdomain>
    http:
      paths:
        - path: /
          backend:
            serviceName: quickstart-es-http #if you want to expose Kibana use quickstart-kp-http instead
            servicePort: 9200 
